# Site settings
title: "Tombo Notes"
email: nil
description: >- # this means to ignore newlines until "baseurl:"
  調べた、試したことのノート
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pojiro.github.io"
icon: "/favicon.ico"

# Global Configuration
safe: false
disable_disk_cache: false
ignore_theme_config: true
timezone: "Asia/Tokyo"
encoding: "utf-8"
exclude:
  # default
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # added
  - Makefile
  - README.md
  - package.json
  - package-lock.json
  - tailwind.config.js

# Front Matter Global, https://jekyllrb.com/docs/permalinks/#global
permalink: /:year/:month/:day/:title:output_ext

# Markdown Options
markdown: CommonMark
commonmark:
  options: ["FOOTNOTES"]
  extensions: ["autolink", "strikethrough", "table", "tasklist"]

# Build Command Options
show_drafts: false
future: false
unpublished: false
lsi: false
force_polling: false
verbose: true
quiet: false
incremental: true
profile: true
strict_front_matter: true

# Plugin Options
## jekyll-paginate
paginate: 5
paginate_path: "page/:num"
## jekyll-seo-tag
author:
  name: "pojiro"
  url: "https://github.com/pojiro"
twitter:
  username: "pojiro3"
  card: "summary"
locale: "ja_JP"
